(defpackage "SB-NIBBLES-TESTS"
  (:use "CL" "SB-RT")
  (:import-from "SB-NIBBLES" "%CHECK-BOUND"))
(in-package "SB-NIBBLES-TESTS")

(macrolet ((define-%check-bound-test (bound n-bytes index vector-constantp index-constantp)
             (let ((expected (if (<= 0 index (- bound n-bytes)) index :good)))
               `(deftest ,(intern (format nil "%CHECK-BOUND.~D.~D,~A.~D,~A"
                                          n-bytes
                                          bound vector-constantp
                                          index index-constantp))
                    (let* ((v (make-array 0 :element-type '(unsigned-byte 8)))
                           (form `(lambda (,@',(unless vector-constantp '(bound)) ,@',(unless index-constantp '(index)))
                                   (%check-bound ,v ,',(if vector-constantp bound 'bound) ,',(if index-constantp index 'index) ,',n-bytes)))
                           (fun (compile nil form)))
                      (handler-case (funcall fun ,@(unless vector-constantp (list bound)) ,@(unless index-constantp (list index)))
                        (type-error () ,(if (eq expected :good) :good :bad))))
                  ,expected)))
           (define-%check-bound-tests (bound n-bytes index)
             `(progn
                (define-%check-bound-test ,bound ,n-bytes ,index nil nil)
                (define-%check-bound-test ,bound ,n-bytes ,index nil t)
                (define-%check-bound-test ,bound ,n-bytes ,index t nil)
                (define-%check-bound-test ,bound ,n-bytes ,index t t)))
           (define-%check-bound-tests-for-n-bytes (n-bytes)
             `(progn
                (define-%check-bound-tests 0 ,n-bytes ,(- n-bytes))
                (define-%check-bound-tests 0 ,n-bytes 0)
                (define-%check-bound-tests 0 ,n-bytes ,most-positive-fixnum)
                (define-%check-bound-tests ,(1- n-bytes) ,n-bytes -1)
                (define-%check-bound-tests ,(1- n-bytes) ,n-bytes 0)
                (define-%check-bound-tests ,(1- n-bytes) ,n-bytes 1)
                (define-%check-bound-tests ,n-bytes ,n-bytes -1)
                (define-%check-bound-tests ,n-bytes ,n-bytes 0)
                (define-%check-bound-tests ,n-bytes ,n-bytes 1)
                (define-%check-bound-tests ,(1- array-dimension-limit) ,n-bytes -1)
                (define-%check-bound-tests ,(1- array-dimension-limit) ,n-bytes 0)
                (define-%check-bound-tests ,(1- array-dimension-limit) ,n-bytes ,(- array-dimension-limit n-bytes 2))
                (define-%check-bound-tests ,(1- array-dimension-limit) ,n-bytes ,(- array-dimension-limit n-bytes 1))
                (define-%check-bound-tests ,(1- array-dimension-limit) ,n-bytes ,(- array-dimension-limit n-bytes 0)))))
  (define-%check-bound-tests-for-n-bytes 2)
  (define-%check-bound-tests-for-n-bytes 4)
  (define-%check-bound-tests-for-n-bytes 8)
  (define-%check-bound-tests-for-n-bytes 16))

(deftest %check-bound.default-policy.not-flushable
    (let* ((v (make-array 0 :element-type '(unsigned-byte 8)))
           (form `(lambda (x y)
                    (%check-bound ,v x y 2)
                    t))
           (fun (compile nil form)))
      (handler-case (funcall fun 0 0)
        (type-error () :good)))
  :good)

(deftest %check-bound.explicit-policy.not-flushable
    (let* ((v (make-array 0 :element-type '(unsigned-byte 8)))
           (form `(lambda (x y)
                    (declare (optimize (safety 0) (speed 3) (sb-c::insert-array-bounds-checks 3)))
                    (%check-bound ,v x y 2)
                    t))
           (fun (compile nil form)))
      (handler-case (funcall fun 0 0)
        (type-error () :good)))
  :good)

(deftest %check-bound.explicit-policy.flushable
    (let* ((v (make-array 0 :element-type '(unsigned-byte 8)))
           (form `(lambda (x y)
                    (declare (optimize (safety 3) (speed 0) (sb-c::insert-array-bounds-checks 0)))
                    (%check-bound ,v x y 2)
                    t))
           (fun (compile nil form)))
      (handler-case (funcall fun 0 0)
        (type-error () :bad)))
  t)

(macrolet ((def-ref-tests (name n-bytes signedp le-p)
             `(progn
                (def-ref-test ,name ,n-bytes ,signedp ,le-p nil nil)
                (def-ref-test ,name ,n-bytes ,signedp ,le-p nil t)
                (def-ref-test ,name ,n-bytes ,signedp ,le-p t nil)))
           (def-ref-test (name n-bytes signedp le-p vector-constantp indexes-constantp)
             `(deftest ,(intern (format nil  "~A.~A.~A" name vector-constantp indexes-constantp))
                  (let* ((v (make-array 256 :element-type '(unsigned-byte 8) :initial-contents (loop for x below 256 collect x)))
                         (form
                           ,(cond
                              (vector-constantp ``(lambda (index1 index2)
                                                    (let ((r1 (,',name ,v index1))
                                                          (r2 (,',name ,v index2)))
                                                      (list r1 r2))))
                              (indexes-constantp ``(lambda (vector)
                                                     (let ((r1 (,',name vector 0))
                                                           (r2 (,',name vector ,(- 256 ,n-bytes))))
                                                       (list r1 r2))))
                              (t ``(lambda (vector index1 index2)
                                     (let ((r1 (,',name vector index1))
                                           (r2 (,',name vector index2)))
                                       (list r1 r2))))))
                         (fun (compile nil form)))
                    (funcall fun ,@(unless vector-constantp '(v)) ,@(unless indexes-constantp (list 0 (- 256 n-bytes)))))
                ,(flet ((ur (list)
                          (reduce (lambda (x y) (+ (* x 256) y)) (if le-p (reverse list) list))))
                   (let* ((u1 (ur (loop for x from 0 below n-bytes collect x)))
                          (u2 (ur (loop for x from (- 256 n-bytes) below 256 collect x)))
                          (s2 (dpb u2 (byte (* n-bytes 8) 0) -1)))
                     (list u1 (if signedp s2 u2)))))))
  (def-ref-tests sb-nibbles::ub16ref/be 2 nil nil)
  (def-ref-tests sb-nibbles::ub16ref/le 2 nil t)
  (def-ref-tests sb-nibbles::sb16ref/be 2 t nil)
  (def-ref-tests sb-nibbles::sb16ref/le 2 t t)

  (def-ref-tests sb-nibbles::ub32ref/be 4 nil nil)
  (def-ref-tests sb-nibbles::ub32ref/le 4 nil t)
  (def-ref-tests sb-nibbles::sb32ref/be 4 t nil)
  (def-ref-tests sb-nibbles::sb32ref/le 4 t t)

  (def-ref-tests sb-nibbles::ub64ref/be 8 nil nil)
  (def-ref-tests sb-nibbles::ub64ref/le 8 nil t)
  (def-ref-tests sb-nibbles::sb64ref/be 8 t nil)
  (def-ref-tests sb-nibbles::sb64ref/le 8 t t))

(macrolet ((def-set-tests (name n-bytes signedp le-p)
             `(progn
                (def-set-test ,name ,n-bytes ,signedp ,le-p nil)
                (def-set-test ,name ,n-bytes ,signedp ,le-p t)))
           (def-set-test (name n-bytes signedp le-p indexes-constantp)
             `(deftest ,(intern (format nil  "~A.~A" name indexes-constantp))
                  (let* ((v (make-array 256 :element-type '(unsigned-byte 8)))
                         (form
                           ,(cond
                              (indexes-constantp
                               ``(lambda (vector new-value1 new-value2)
                                   (,',name vector 0 new-value1)
                                   (,',name vector ,(- 256 ,n-bytes) new-value2)
                                   (list
                                    (coerce (subseq vector 0 ,',n-bytes) 'list)
                                    (coerce (subseq vector ,(- 256 ,n-bytes)) 'list))))
                              (t ``(lambda (vector index1 index2 new-value1 new-value2)
                                     (,',name vector index1 new-value1)
                                     (,',name vector index2 new-value2)
                                     (list
                                      (coerce (subseq vector 0 ,',n-bytes) 'list)
                                      (coerce (subseq vector ,(- 256 ,n-bytes)) 'list))))))
                         (fun (compile nil form)))
                    ,(flet ((ur (list) (reduce (lambda (x y) (+ (* x 256) y)) (if le-p (reverse list) list))))
                       `(let* ((new-value1 ,(ur (loop for x from 0 below n-bytes collect x)))
                               (new-value2 ,(let ((u2 (ur (loop for x from (- 256 n-bytes) below 256 collect x))))
                                              (if signedp (dpb u2 (byte (* n-bytes 8) 0) -1) u2))))
                          (funcall fun v ,@(unless indexes-constantp (list 0 (- 256 n-bytes))) new-value1 new-value2))))
                ,(list (loop for x from 0 below n-bytes collect x) (loop for x from (- 256 n-bytes) below 256 collect x)))))
  (def-set-tests sb-nibbles::ub16set/be 2 nil nil)
  (def-set-tests sb-nibbles::ub16set/le 2 nil t)
  (def-set-tests sb-nibbles::sb16set/be 2 t nil)
  (def-set-tests sb-nibbles::sb16set/le 2 t t)

  (def-set-tests sb-nibbles::ub32set/be 4 nil nil)
  (def-set-tests sb-nibbles::ub32set/le 4 nil t)
  (def-set-tests sb-nibbles::sb32set/be 4 t nil)
  (def-set-tests sb-nibbles::sb32set/le 4 t t)

  (def-set-tests sb-nibbles::ub64set/be 8 nil nil)
  (def-set-tests sb-nibbles::ub64set/le 8 nil t)
  (def-set-tests sb-nibbles::sb64set/be 8 t nil)
  (def-set-tests sb-nibbles::sb64set/le 8 t t))
